name: st_gui
channels:
- nodefaults
dependencies:
- python=3.7
- pip
- pip:
  - -r requirements.txt
install --admin "--admin=\$INSTALL_ENV_DIR" conda list --prefix "\$INSTALL_ENV_DIR" conda list --prefix "\$INSTALL_ENV_DIR" --explicit ">" "/Users/admin/Downloads/install.ps1

